// Generated by CoffeeScript 1.6.2
var EyebrowseBrowser, browsers, cmd, e, eyebrowse, _i, _len;

eyebrowse = require("eyebrowse");

EyebrowseBrowser = (function() {
  EyebrowseBrowser.prototype.name = "Eyebrowse";

  EyebrowseBrowser.prototype.DEFAULT_CMD = {
    linux: eyebrowse.path,
    darwin: eyebrowse.path,
    win32: eyebrowse.path
  };

  EyebrowseBrowser.prototype.ENV_CMD = "EYEBROWSE_BIN";

  /*`
  */


  function EyebrowseBrowser(baseBrowserDecorator, name, args) {
    this.args = args;
    baseBrowserDecorator(this);
    this.browserName = name.split("eyebrowse:").join("").replace(":", "@");
    this._getOptions = this.constructor.prototype._getOptions;
  }

  /*
  */


  EyebrowseBrowser.prototype._start = function(url) {
    return console.log(arguments);
  };

  /*
  */


  EyebrowseBrowser.prototype._getCommand = function() {
    return console.log(arguments);
  };

  /*
  */


  EyebrowseBrowser.prototype._getOptions = function(url) {
    return ["start", this.browserName, url];
  };

  /*
  */


  EyebrowseBrowser.$inject = ["baseBrowserDecorator", "name", "args"];

  return EyebrowseBrowser;

})();

try {
  browsers = require(process.cwd() + "/.browsers");
} catch (_error) {
  e = _error;
  browsers = ["Chrome:Latest", "Safari:Latest", "Opera:Latest", "Firefox:Latest", "IE:Latest"];
}

for (_i = 0, _len = browsers.length; _i < _len; _i++) {
  cmd = browsers[_i];
  exports["launcher:eyebrowse:" + cmd] = ["type", EyebrowseBrowser];
}
